### ISSUE TITLE
Can We Change the Namespace?

### ISSUE THREAD

**Issue by aljawaid** [creecros/Bak2topbotm#3]
Hello

Can I change the namespace for this and cleanup the code structure to make it more inline with the Kanboard Skeleton Plugin?

I was thinking of changing `Bak2topbotm` to `TaskScroller` to make it more meaningful specifically for tasks which is what the plugin does.  Or maybe abandon this plugin altogether and replace it with `KanboardScroller` and show the up/down buttons across the interface.

I know users would need to re-install the plugin because of the new namespace.

Also, if you dont plan any work on it, can you make me a maintainer please so I can remove the wiki section?

Your thoughts would be appreciated.

**Comment by creecros** [comment]
Welcome to change whatever you want. Long as I don't have to do it :)

**Comment by aljawaid** [comment]
Change my level in the repo, otherwise I cant change the folder etc please

**Comment by creecros** [comment]
I have no idea how
